project_name: dns2ip-templater

before:
  hooks:
    - go mod tidy

builds:
  - id: dns2ip-templater_binaries
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7

archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
      arm: armhf

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  footer: |
    That's all for this new release of dns2ip-templater {{ .Tag }}!
